const lessonTitle = "有输有赢才是人生";

const lessonData = [
    // 正文第 1 段
    ["今天", "jīn tiān", "today", "hari ini"],
    ["你放学", "nǐ fàng xué", "you after school", "kamu balik sekolah"],
    ["回家", "huí jiā", "return home", "pulang ke rumah"],
    ["，", "", "", ""],
    ["我问你", "wǒ wèn nǐ", "I ask you", "saya bertanya kamu"],
    ["“", "", "", ""],
    ["在学校", "zài xué xiào", "at school", "di sekolah"],
    ["好吗", "hǎo ma", "good or not", "baik kah"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["你没搭腔", "nǐ méi dā qiāng", "you did not answer", "kamu tidak menyahut / membisu"],
    ["，", "", "", ""],
    ["我就觉得", "wǒ jiù jué de", "I then felt", "saya terus berasa"],
    ["不对劲", "bú duì jìn", "something is wrong / fishy", "ada yang tidak kena / pelik"],
    ["，", "", "", ""],
    ["果然", "guǒ rán", "sure enough / as expected", "rupa-rupanya / sememangnya"],
    ["走进", "zǒu jìn", "walk into", "melangkah masuk ke"],
    ["厨房", "chú fáng", "kitchen", "dapur"],
    ["，", "", "", ""],
    ["看见你", "kàn jiàn nǐ", "saw you", "melihat kamu"],
    ["正搂着", "zhèng zài lǒu zhe", "currently hugging", "sedang memeluk"],
    ["妈妈", "mā ma", "mother", "emak"],
    ["，", "", "", ""],
    ["眼睛", "yǎn jing", "eyes", "mata"],
    ["红红的", "hóng hóng de", "reddened", "kemerah-merahan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段
    ["“", "", "", ""],
    ["是身体", "shì shēn tǐ", "is it body", "adakah tubuh badan"],
    ["不舒服", "bù shū fu", "uncomfortable / unwell", "tidak sihat / kurang selesa"],
    ["吗", "ma", "particle", "kah"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["我问你", "wǒ wèn nǐ", "I ask you", "Saya bertanya kamu"],
    ["。", "", "", ""],
    ["你没答", "nǐ méi dá", "you did not answer", "Kamu tidak menjawab"],
    ["，", "", "", ""],
    ["妈妈", "mā ma", "mother", "emak pula"],
    ["答了", "dá le", "answered", "menjawab"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["只是", "zhǐ shì", "just / only", "sekadar"],
    ["流鼻涕", "liú bí tì", "running nose", "selesema / meleleh hingus"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段
    ["我", "wǒ", "I", "Saya"],
    ["又问你", "yòu wèn nǐ", "again asked you", "pula bertanya kamu"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["是什么", "shì shén me", "is it what", "adakah hal apa"],
    ["没考好", "méi kǎo hǎo", "did not exam well", "tidak dapat keputusan baik"],
    ["吗", "ma", "particle", "kah"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段
    ["你点了一下头", "nǐ diǎn le yí xià tóu", "you nodded head once", "Kamu menganggukkan kepala sekali"],
    ["，", "", "", ""],
    ["眼泪", "yǎn lèi", "tears", "air mata"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["像", "xiàng", "resembles / like", "bagaikan / seperti"],
    ["断线珠子", "duàn xiàn zhū zi", "broken string of pearls", "butiran mutiara yang putus tali"],
    ["似的", "shì de", "resembling", "sedemikian"],
    ["滚下来", "gǔn xià lái", "rolling down", "mengalir tumpah turun"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["历史", "lì shǐ", "History (Subject)", "Sejarah"],
    ["没考好", "méi kǎo hǎo", "did not exam well", "tidak kǎo baik"],
    ["，", "", "", ""],
    ["才考了", "cái kǎo le", "only scored", "hanya mendapat score"],
    ["84分", "bā shí sì fēn", "84 marks", "lapan puluh empat markah"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段
    ["“", "", "", ""],
    ["别人", "bié rén", "Others / classmates", "Orang lain semuanya"],
    ["都", "dōu", "all", "pun"],
    ["考好了", "kǎo hǎo le", "scored well", "dapat score baik"],
    ["吗", "ma", "particle", "kah"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["我问", "wǒ wèn", "I asked", "saya bertanya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段
    ["“", "", "", ""],
    ["好多人", "hǎo duō rén", "A lot of people", "Ramai orang"],
    ["考得", "kǎo de", "scored (description)", "mendapat score yang"],
    ["比我好", "bǐ wǒ hǎo", "better than me", "lebih baik daripada saya"],
    ["。”", "", "", ""],
    ["你嘟着嘴", "nǐ dū zhe zuǐ", "you pouted lips", "Kamu memuncungkan mulut"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["我从来没", "wǒ cóng lái méi", "I never before", "Saya sepanjang hidup tidak pernah"],
    ["考过", "kǎo guò", "scored exam", "mendapat score"],
    ["这么烂", "zhè me làn", "so rotten / so bad", "seburuk sebegini"],
    ["。”", "", "", ""],
    ["接着", "jiē zhe", "Right after / then", "Seterusnya / kemudian"],
    ["一转身", "yì zhuǎn shēn", "once turning body around", "pusing badan sahaja terus"],
    ["，", "", "", ""],
    ["冲上楼去", "chōng shàng lóu qù", "rushed upstairs", "meluru naik ke tingkat atas"],
    ["。", "", "", ""],
    ["我也", "wǒ yě", "I also", "Saya pun turut"],
    ["跟上楼", "gēn shàng lóu", "followed upstairs", "ikut naik ke tingkat atas"],
    ["，", "", "", ""],
    ["你对我的", "nǐ duì wǒ de", "you towards me", "kamu terhadap saya punya"],
    ["没好气地", "méi hǎo qì de", "snappishly / testily", "dengan nada merungut / kurang senang"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不要理我", "bú yào lǐ wǒ", "don't mind me / leave me alone", "jangan pedulikan saya"],
    ["，", "", "", ""],
    ["我哭一下", "wǒ kū yí xià", "I cry a bit", "biarkan saya menangis sekejap"],
    ["就好了", "jiù hǎo le", "then will be fine", "barulah akan lega"],
    ["。”", "", "", ""],
    ["果然", "guǒ rán", "Sure enough", "Sememangnya rupa-rupanya"],
    ["隔一阵", "gé yí zhèn", "after a while", "selang beberapa ketika"],
    ["，", "", "", ""],
    ["你已经", "yǐ jīng", "you already", "kamu sudah pun"],
    ["平复", "píng fù", "calmed down / recovered", "tenang semula心"],
    ["，", "", "", ""],
    ["坐到", "zuò dào", "sat down at", "duduk di"],
    ["书桌前面", "shū zhuō qián mian", "in front of the desk", "depan meja tulis"],
    ["，", "", "", ""],
    ["弯身", "wān shēn", "bending body", "membongkokkan badan"],
    ["翻书包", "fān shū bāo", "rummaged schoolbag", "menyelongkar beg sekolah"],
    ["，", "", "", ""],
    ["拿出", "ná chū", "took out", "mengeluarkan"],
    ["厚厚的", "hòu hòu de", "thick", "yang tebal-tebal punya"],
    ["历史课本", "lì shǐ kè běn", "history textbook", "buku teks Sejarah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段
    ["我认识", "wǒ rèn shi", "I recognized", "Saya kenal"],
    ["那课本", "nà kè běn", "that textbook", "buku teks itu"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["前几天", "qián jǐ tiān", "a few days ago", "beberapa hari yang lalu"],
    ["你留在", "nǐ liú zài", "you left at", "kamu tinggalkan di atas"],
    ["客厅桌上", "kè tīng zhuō shàng", "living room table", "meja ruang tamu"],
    ["，", "", "", ""],
    ["我曾经", "wǒ céng jīng", "I once before", "saya pernah suatu masa"],
    ["翻过", "fān guò", "flipped through", "menyelongkar selak membaca"],
    ["，", "", "", ""],
    ["里面", "lǐ miàn", "inside", "di dalam"],
    ["除了", "chú le", "besides / apart from", "selain daripada"],
    ["讲历史", "jiǎng lì shǐ", "talking about history", "menceritakan sejarah"],
    ["，", "", "", ""],
    ["还附带了", "hái fù dài le", "also accompanied / attached", "turut disertakan bersama"],
    ["许多相关的", "xǔ duō xiāng guān de", "many relevant's", "banyak yang berkaitan punya"],
    ["世界名著", "shì jiè míng zhù", "world literary classics", "karya agung dunia"],
    ["。", "", "", ""],
    ["记得", "jì de", "Remembered", "Mengingati"],
    ["当时", "dāng shí", "at that time", "pada masa itu"],
    ["我问你", "wǒ wèn nǐ", "I asked you", "saya bertanya kamu sama ada"],
    ["是不是", "shì bú shì", "whether or not it was", "ia adalah ataupun tidak"],
    ["课外读物", "kè wài dú wù", "extracurricular reading materials", "buku bacaan luar kelas"],
    ["，", "", "", ""],
    ["听你说是", "tīng nǐ shuō shì", "hearing you say it was", "apabila mendengar kamu kata ia adalah"],
    ["课本时", "kè běn shí", "textbook when", "buku teks waktu itu"],
    ["，", "", "", ""],
    ["还赞美", "hái zàn měi", "also praised", "malah turut memuji bahawa"],
    ["那书", "nà shū", "that book", "buku itu"],
    ["编得", "biān de", "edited / compiled (description)", "disusun dengan"],
    ["真生动", "zhēn shēng dòng", "truly vivid / lively", "amat hidup berseri sekali"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段
    ["我坐在", "wǒ zuò zài", "I sat on", "Saya duduk di atas"],
    ["你的床上", "nǐ de chuáng shàng", "your bed top", "kamu punya katil atas"],
    ["，", "", "", ""],
    ["看你", "kàn nǐ", "watching you", "melihat kamu"],
    ["拿出", "ná chū", "taking out", "mengeluarkan"],
    ["考卷", "kǎo juàn", "exam paper", "kertas ujian / kertas soalan"],
    ["来检查", "lái jiǎn chá", "to check / examine", "untuk memeriksa semula"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段
    ["“", "", "", ""],
    ["是错了吗", "shì cuò le ma", "is it wrong", "Adakah silap buat kah"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["我又问你", "wǒ yòu wèn nǐ", "I again asked you", "saya pula bertanya kamu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段
    ["“", "", "", ""],
    ["是错了", "shì cuò le", "Is wrong", "Memang silap buat"],
    ["。”", "", "", ""],
    ["你说", "nǐ shuō", "you said", "Kamu berkata"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["但我真不懂", "wǒ zhēn bù dǒng", "but I truly don't understand", "tetapi saya sungguh tidak paham"],
    ["，", "", "", ""],
    ["为什么自己", "wèi shén me zì jǐ", "why oneself", "mengapakah diri sendiri"],
    ["会那么糊涂", "huì nà me hú tu", "could be so muddled / careless", "boleh sebegitu cuai / bodoh sekali"],
    ["，", "", "", ""],
    ["别人", "bié rén", "others", "orang lain semuanya"],
    ["都没错", "dōu méi cuò", "all not wrong", "langsung tidak silap"],
    ["，", "", "", ""],
    ["连最烂的", "lián zuì làn de", "even the worst", "bahkan budak lelaki yang paling corot / malas sekali"],
    ["男生", "nán shēng", "boy", "pun"],
    ["都会的", "dōu huì de", "all know how to do's", "pandai buat punya beberapa buah"],
    ["几个", "jǐ gè", "a few", "perkara"],
    ["‘军事强国’", "jūn shì qiáng guó", "military powers", "kuasa besar askar / negara ketenteraan kuat"],
    ["，", "", "", ""],
    ["我却会错", "wǒ què huì cuò", "I conversely made mistake", "saya sebaliknya boleh salah buat"],
    ["！", "", "", ""],
    ["忘了写", "wàng le xiě", "forgot to write", "terlupa tulis nama negara"],
    ["德国", "dé guó", "Germany", "Jerman"],
    ["。”", "", "", ""],
    ["说着说着", "shuō zhe shuō zhe", "As speaking further", "Sambil bercakap-cakap itu"],
    ["你又哭了", "nǐ yòu kū le", "you again cried", "kamu sekali lagi menangis mencucurkan air mata"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while on one hand", "sambil"],
    ["呜呜地哭", "wū wū de kū", "wailing / weeping aloud", "menangis teresak-esak terisak-isak"],
    ["，", "", "", ""],
    ["一边说", "yì biān shuō", "while on the other hand speaking", "sambil berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我不是没念", "wǒ bú shì méi niàn", "I wasn't not studying", "saya bukannya tidak membaca buku teks"],
    ["，", "", "", ""],
    ["我念了啊", "wǒ niàn le ā", "I studied indeed", "saya dah baca dah lah"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段
    ["孩子", "hái zi", "Child", "Anakku"],
    ["！", "", "", ""],
    ["看你哭", "kàn nǐ kū", "watching you cry", "Melihat kamu menangis"],
    ["，", "", "", ""],
    ["我也很", "wǒ yě hěn", "I also very", "saya pun turut tersangat"],
    ["伤心", "shāng xīn", "sad / heartbroken", "sedih hati"],
    ["，", "", "", ""],
    ["尤其", "yóu qí", "especially", "terutamanya kebetulan"],
    ["当你说", "dāng nǐ shuō", "when you said", "apabila kamu berkata bahawa"],
    ["别的同学", "bié de tóng xué", "other classmates", "rakan sekelas yang lain"],
    ["问你成绩时", "wèn nǐ chéng jī shí", "asked your result when", "bertanya keputusan exam kamu waktu itu"],
    ["，", "", "", ""],
    ["我可以想象", "wǒ kě yǐ xiǎng xiàng", "I can imagine", "saya boleh membayangkan"],
    ["你当时的", "nǐ dāng shí de", "your at that time's", "kamu punya pada masa itu punya"],
    ["尴尬", "gān gà", "embarrassment / awkwardness", "rasa janggal / malu segan"],
    ["，", "", "", ""],
    ["因为你", "yīn wèi nǐ", "because you", "kerana kamu punya"],
    ["成绩", "chéng jī", "academic results", "keputusan akademik selama ini"],
    ["从来都是", "cóng lái dōu shì", "always all along were", "sentiasa kekal adalah yang"],
    ["最好的", "zuì hǎo de", "the best", "paling cemerlang sekali"],
    ["。", "", "", ""],
    ["但我也要", "dàn wǒ yě yào", "But I also want to", "Namun saya pun mahu"],
    ["对你说", "duì nǐ shuō", "say to you", "berkata kepada kamu bahawa"],
    ["，", "", "", ""],
    ["这世界上", "zhè shì jiè shàng", "in this world", "di dalam dunia ini"],
    ["并非", "bìng fēi", "is by no means / not exactly", "bukannya semestinya"],
    ["一分耕耘", "yī fēn gēng yún", "an ace of plowing (effort)", "setitik usaha gigih"],
    ["，", "", "", ""],
    ["就一定有", "jiù yí dìng yǒu", "then definitely has", "pasti akan memperoleh"],
    ["一分收获", "yī fēn shōu huò", "an ace of harvest (reward)", "setitik hasil tuaian rezeki"],
    ["。", "", "", ""],
    ["有时候", "yǒu shí hou", "Sometimes", "Kadang-kala"],
    ["，", "", "", ""],
    ["你可能", "nǐ kě néng", "you probably", "kamu mungkin"],
    ["用的", "yòng de", "used", "menggunakan buah"],
    ["种子不好", "zhǒng zi bù hǎo", "seeds are not good", "benih tanaman yang kurang bermutu"],
    ["、", "", "", ""],
    ["水土不对", "shuǐ tǔ bú duì", "soil and water are wrong", "tanah dan air tidak sesuai sesuai"],
    ["，", "", "", ""],
    ["再遇上", "zài yù shàng", "again encounter", "ditambah pula berdepan dengan"],
    ["坏天气", "huài tiān qì", "bad weather", "cuaca buruk musibah"],
    ["，", "", "", ""],
    ["结果", "jié guǒ", "as a result / in the end", "kesudahannya"],
    ["下了", "xià le", "exerted / put in", "mencurahkan sehabis-habis"],
    ["最大的功夫", "zuì dà de gōng fu", "the greatest effort / hard work", "usaha tenaga yang paling besar sekali"],
    ["，", "", "", ""],
    ["反不如", "fǎn bù rú", "conversely not as good as", "sebaliknya langsung tidak setanding dengan"],
    ["那些", "nà xiē", "those who", "mereka yang kebetulan mendapat"],
    ["天时地利人和", "tiān shí dì lì rén hé", "favorable climate, geographical and human conditions", "tuah masa, kesesuaian tempat dan sokongan manusia"],
    ["都对", "dōu duì", "all correct", "semuanya tepat belaka"],
    ["，", "", "", ""],
    ["却没努力的", "què méi nǔ lì de", "yet didn't work hard's", "namun langsung tidak malas rajin berusaha punya"],
    ["人", "rén", "people", "manusia punya"],
    ["收获来得好", "shōu huò lái de hǎo", "harvest comes out better", "hasil rezeki tuaian datang lebih lumayan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段
    ["你也要", "nǐ yě yào", "You also need to", "Kamu pun perlu juga"],
    ["知道", "zhī dào", "know", "tahu bahawa"],
    ["，", "", "", ""],
    ["知识", "zhī shi", "knowledge", "ilmu pengetahuan"],
    ["不见得", "bú jiàn dé", "not necessarily", "tidak semestinya"],
    ["全由", "quán yóu", "completely from", "sepenuhnya datang daripada dalam"],
    ["课本里", "kè běn lǐ", "inside textbooks", "buku teks sahaja diperoleh"],
    ["得来", "dé lái", "obtained / derived", "didapati"],
    ["，", "", "", ""],
    ["那些", "nà xiē", "those", "mereka yang"],
    ["最顽皮的", "zuì wán pí de", "the most mischievous / naughty", "paling nakal dan degil sekali punya"],
    ["男生", "nán shēng", "boys", "budak-budak lelaki"],
    ["，", "", "", ""],
    ["可能", "kě néng", "probably", "mungkin sahaja"],
    ["成天", "chéng tiān", "all day long", "sepanjang hari suntuk"],
    ["阅读", "yuè dú", "reading", "membaca novel"],
    ["战争小说", "zhàn zhēng xiǎo shuō", "war novels", "kisah peperangan askar"],
    ["，", "", "", ""],
    ["他们的", "tā men de", "their", "mereka punya"],
    ["长辈", "zhǎng bèi", "elders / seniors", "orang tua generasi dahulu / datuk nenek"],
    ["可能", "kě néng", "probably", "mungkin pernah"],
    ["参加过", "cān jiā guò", "participated in before", "menyertai perang"],
    ["二次大战", "èr cì dà zhàn", "World War II", "Perang Dunia Kedua"],
    ["，", "", "", ""],
    ["在家", "zài jiā", "at home", "di dalam rumah selalu"],
    ["总说", "zǒng shuō", "always spoke of", "asyik menceritakan tentang"],
    ["当年的", "dāng nián de", "those years' / past", "pada zaman itu punya"],
    ["往事", "wǎng shì", "past events / history", "kisah-kisah lama lama"],
    ["；", "", "", ""],
    ["他们又可能", "tā men yòu kě néng", "they again probably", "mereka pula mungkin juga jenis yang"],
    ["爱读报", "ài dú bào", "love reading newspapers", "suka membaca akhbar surat khabar"],
    ["、", "", "", ""],
    ["看", "kàn", "watching", "menonton siaran"],
    ["历史频道", "lì shǐ pín dào", "History Channel", "Saluran Sejarah (History Channel)"],
    ["和", "hé", "and", "dan"],
    ["益智问答", "yì zhì wèn dá", "quiz / trivia games", "kuiz teka-teki uji minda bijak"],
    ["节目", "jié mù", "programs / shows", "siaran rancangan"],
    ["，", "", "", ""],
    ["他们看似", "tā men kàn sì", "they seemingly looked like", "mereka kelihatan pada zahirnya rupa"],
    ["没有", "méi yǒu", "did not have", "tidak ada"],
    ["认真读书", "rèn zhēn dú shū", "studying hard", "bersungguh-sungguh mengulangi pelajaran"],
    ["，", "", "", ""],
    ["却因为", "què yīn wèi", "yet because of", "sebaliknya adalah disebabkan oleh"],
    ["周遭的", "zhōu zāo de", "surrounding's", "persekitaran sekeliling punya"],
    ["氛围", "fēn wéi", "atmosphere / ambiance", "suasana aura"],
    ["，", "", "", ""],
    ["而在", "ér zài", "and thereby in", "lalu di dalam keadaan"],
    ["自然中", "zì rán zhōng", "nature within / naturally", "semulajadi"],
    ["学习了", "xué xí le", "learned", "telah menyerap ilmu belajar dah"],
    ["。", "", "", ""],
    ["你甚至", "nǐ shèn zhì", "You even", "Kamu malah bahkan"],
    ["可以猜", "kě yǐ cāi", "can guess", "boleh membuat tekaan bahawa"],
    ["，", "", "", ""],
    ["他们玩的", "tā men wán de", "they played's", "mereka main punya permainan"],
    ["战争", "zhàn zhēng", "war", "perang askar"],
    ["电脑游戏", "diàn nǎo yóu xì", "computer games", "game komputer"],
    ["，", "", "", ""],
    ["都有帮助", "dōu yǒu bāng zhù", "all have help", "pun semuanya membawa bantuan besar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段
    ["有句俗话", "yǒu jù sú huà", "There is a proverb / saying", "Ada sebaris pepatah melayu orang tua"],
    ["——", "", "", ""],
    ["“", "", "", ""],
    ["有意栽花", "yǒu yì zāi huā", "intentionally planting flowers", "dengan sengaja menanam pokok bunga"],
    ["花不开", "huā bù kāi", "flowers do not blossom", "bunga langsung tidak mahu berkembang kembang"],
    ["，", "", "", ""],
    ["无心插柳", "wú xīn chā liǔ", "unintentionally sticking willow branches", "tanpa niat tercacak batang pokok buluh"],
    ["柳成荫", "liǔ chéng yīn", "willows form a shade", "buluh tumbuh subur merimbun redup"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["也是", "yě shì", "also is", "pun adalah membawa"],
    ["这个道理", "zhè gè dào lǐ", "this same reason / truth", "rasional yang sebegini sama sahaja"],
    ["。", "", "", ""],
    ["不见得", "bú jiàn dé", "Not necessarily", "Tidak semestinya hal yang"],
    ["你最用心的", "nǐ zuì yòng xīn de", "you exerted most mind's", "kamu paling curah tumpuan usaha punya"],
    ["，", "", "", ""],
    ["就一定", "jiù yí dìng", "then definitely", "pasti akan memperoleh"],
    ["成功", "chéng gōng", "succeed / success", "kejayaan cemerlang"],
    ["；", "", "", ""],
    ["反而", "fǎn ér", "on the contrary / instead", "sebaliknya pula kejayaan"],
    ["可能", "kě neng", "probably", "mungkin datang dari"],
    ["无心中", "wú xīn zhōng", "mindlessness within / unintentionally", "keadaan tanpa sengaja di dalam"],
    ["造成的", "zào chéng de", "caused's", "tercipta punya sehelai"],
    ["机缘", "jī yuán", "opportunity / luck / coincidence", "peluang kebetulan / tuah nasib"],
    ["，", "", "", ""],
    ["使你获胜", "shǐ nǐ huò shèng", "make you win", "menyebabkan kamu menang johan jua"],
    ["。", "", "", ""],
    ["但是", "dàn shì", "But", "Namun begitu adakah"],
    ["会不会", "huì bú huì", "could it be that / will it or not", "akan menyebabkan"],
    ["因此", "yīn cǐ", "because of this", "oleh sebab perkara ini"],
    ["，", "", "", ""],
    ["你就不必", "nǐ jiù bú bì", "you then no need to", "kamu terus tidak payah lagi untuk"],
    ["耕耘了呢", "gēng yún le ne", "plow / work hard anymore", "rajin berusaha mencurahkan tenaga kah"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第 14 段
    ["错了", "cuò le", "Wrong", "Salah pandangan itu"],
    ["！", "", "", ""],
    ["尽管", "jǐn guǎn", "Although / despite", "Walaupun semestinya sungguhpun"],
    ["不见得", "bú jiàn dé", "not necessarily", "tidak semestinya semata-mata"],
    ["一分耕耘", "yī fēn gēng yún", "an ace of plowing", "setitik usaha rajin"],
    ["能换来", "néng huàn lái", "can exchange back for", "boleh bertukar membawa balik"],
    ["一分收获", "yī fēn shōu huò", "an ace of reward", "setitik rezeki tuaian hasil"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "namun tetap jua"],
    ["耕耘多的人", "gēng yún duō de rén", "people who plow more", "manusia yang mencurahkan lebih banyak usaha punya"],
    ["总能有", "zǒng néng yǒu", "always can have", "pasti sentiasa boleh menikmati"],
    ["较多的", "jiào duō de", "comparatively more's", "lebih banyak sedikit punya"],
    ["收获", "shōu huò", "harvest / rewards", "hasil pulangan tuaian rezeki"],
    ["；", "", "", ""],
    ["这", "zhè", "this", "perkara sebegini"],
    ["就好比", "jiù hǎo bǐ", "exactly resembles", "adalah bagaikan mirip"],
    ["守株", "shǒu zhū", "guarding stump (waiting for rabbits)", "menunggu tunggul kayu di kebun"],
    ["固然可能", "gù rán kě néng", "admittedly probably", "memang diakui akal mungkin sahaja"],
    ["碰上", "pèng shàng", "bump into / encounter", "terserempak bertemu"],
    ["一只", "yì zhī", "one (measure word for rabbit)", "seekor"],
    ["自己", "zì jǐ", "oneself", "diri sendiri punya yang"],
    ["撞上树的", "zhuàng shàng shù de", "crashed into tree's", "terlanggar batang pokok punya"],
    ["兔子", "tù zi", "rabbit", "arnab comel"],
    ["，", "", "", ""],
    ["但绝不可能", "dàn jué bù kě néng", "but absolutely impossible", "namun mustahil sama sekali untuk"],
    ["比得上", "bǐ de shàng", "comparable to / match", "setanding tanding dengan"],
    ["主动出击的", "zhǔ dòng chū jī de", "proactively attacking's", "yang tangkas keluar memburu punya"],
    ["猎人", "liè rén", "hunter", "pemburu binatang"],
    ["。", "", "", ""],
    ["再举个", "zài jǔ gè", "Again give a", "Biar saya bagi satu lagi buah"],
    ["例子吧", "lì zi ba", "example", "contoh teladan lah"],
    ["！", "", "", ""],
    ["我从小", "wǒ cóng xiǎo", "I since childhood", "Saya sejak dari kecil lagi"],
    ["就喜欢", "jiù xǐ huan", "just loved", "memang asyik suka sangat"],
    ["写文章", "xiě wén zhāng", "writing articles / essays", "menulis esei karangan rencana"],
    ["，", "", "", ""],
    ["可是常常", "kě shì cháng cháng", "but frequently / always", "namun kerap kali selalu"],
    ["投稿", "tóu gǎo", "submitting articles for publication", "menghantar karya kiriman esei ke akhbar"],
    ["没几天", "méi jǐ tiān", "not a few days later", "selang tidak berapa hari sahaja"],
    ["，", "", "", ""],
    ["就收到", "jiù shōu dào", "then received", "terus menerima balik"],
    ["厚厚的", "hòu hòu de", "thick", "yang tebal-tebal punya"],
    ["信", "xìn", "letter", "surat kiriman balasan"],
    ["，", "", "", ""],
    ["里面装着", "lǐ miàn zhuāng zhe", "inside packed with", "di dalam koceknya terkandung isi"],
    ["退稿", "tuì gǎo", "rejected manuscripts", "karangan yang ditolak mentah-mentah"],
    ["，", "", "", ""],
    ["主编", "zhǔ biān", "chief editor", "ketua editor / ketua pengarang"],
    ["连一句", "lián yí jù", "even one sentence of", "bahkan sepatah perkataan pun"],
    ["安慰的话", "ān wèi de huà", "consoling words", "kata-kata pujukan tenangkan hati"],
    ["都懒得写", "dōu lǎn de xiě", "all too lazy to write", "langsung malas nak tulis bagi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 15 段
    ["有一阵子", "yǒu yí zhèn zi", "For a period of time", "Ada suatu ketika waktu dahulu"],
    ["，", "", "", ""],
    ["我被退得", "wǒ bèi tuì de", "I was rejected until (description)", "saya digagalkan ditolak karangan sehingga"],
    ["实在", "shí zài", "truly / really", "benar-benar sungguh"],
    ["伤心了", "shāng xīn le", "sad / heartbroken", "patah hati sangat dah"],
    ["，", "", "", ""],
    ["不再投稿", "bú zài tóu gǎo", "no longer submitting articles", "terus merajuk tidak menghantar karya lagi"],
    ["，", "", "", ""],
    ["但是总在", "dàn shì zǒng zài", "but always at the time of", "namun setiap kali ketika"],
    ["翻报的时候", "fān bào de shí hou", "flipping newspapers time", "menyelak-nyelak membaca surat khabar"],
    ["幻想", "huàn xiǎng", "fantasizing / daydreaming", "berkhayal memasang impian angan-angan"],
    ["有自己的", "yǒu zì jǐ de", "having one's own", "ada diri sendiri punya rencana esei"],
    ["文章发表", "wén zhāng fā biǎo", "articles published", "disiarkan keluar cetak"],
    ["。", "", "", ""],
    ["你想想", "nǐ xiǎng xiang", "You think about it", "Kamu cuba fikir elok-elok sekejap"],
    ["，", "", "", ""],
    ["这实际吗", "zhè shí jì ma", "is this realistic / practical", "adakah perkara sebegini logik praktikal kah"],
    ["？", "", "", ""],
    ["我不投稿", "wǒ bù tóu gǎo", "I don't submit articles", "Kalau saya merajuk tidak hantar karya"],
    ["，", "", "", ""],
    ["怎么可能", "zěn me kě néng", "how could it be possible", "bagaimanakah dapat masuk akal boleh"],
    ["有文章发表", "yǒu wén zhāng fā biǎo", "have articles published", "ada esei rencana disiarkan keluar cetak"],
    ["？", "", "", ""],
    ["投稿", "tóu gǎo", "Submitting articles", "Menghantar karya kiriman esei itu"],
    ["固然有", "gù rán yǒu", "admittedly has", "memang diakui ada membawa"],
    ["被退的", "bèi tuì de", "being rejected's", "rasa sakit ditolak punya"],
    ["伤心", "shāng xīn", "sadness", "patah hati luluh"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "namun jika sebaliknya"],
    ["不投稿", "bù tóu gǎo", "not submitting articles", "tidak menghantar karya langsung"],
    ["，", "", "", ""],
    ["就连", "jiù lián", "even", "bahkan langsung kesempatan peluang"],
    ["伤心的机会", "shāng xīn de jī huì", "chance to be sad", "untuk berasa patah hati pun"],
    ["都没了", "dōu méi yǒu le", "all gone / no more", "terus dah tidak ada langsung jua"],
    ["。", "", "", ""],
    ["所以", "suǒ yǐ", "Therefore", "Oleh yang demikian halnya"],
    ["“", "", "", ""],
    ["有意种花", "yǒu yì zhòng huā", "intentionally growing flowers", "manusia jenis yang dengan sengaja menanam bunga"],
    ["花不开", "huā bù kāi", "flowers do not blossom", "bunga langsung tidak mahu kembang kembang punya"],
    ["”", "", "", ""],
    ["的人", "de rén", "people", "punya manusia"],
    ["，", "", "", ""],
    ["唯一的办法", "wéi yī de bàn fǎ", "the only way / solution", "satu-satunya jalan keluar yang tunggal"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "exactly is", "adalah wajib terus untuk"],
    ["继续努力", "jì xù nǔ lì", "continue to work hard", "berterusan gigih berusaha"],
    ["种更多的花", "zhòng gèng duō de huā", "grow more flowers", "menanam lebih banyak pokok bunga lagi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 16 段
    ["记得", "jì de", "Remembered", "Mengingati masa"],
    ["昨天晚餐", "zuó tiān wǎn cān", "yesterday's dinner", "makan malam semalam"],
    ["，", "", "", ""],
    ["婆婆说", "pó po shuō", "Grandmother (paternal) said", "Nenek (mak mentua/ibu bapa) berkata"],
    ["“", "", "", ""],
    ["养孩子", "yǎng hái zi", "rearing children", "membela memelihara anak-anak kecil"],
    ["，", "", "", ""],
    ["忙得要死", "máng de yào sǐ", "busy to death", "tersangat sibuk sampai nak mati rasa"],
    ["，", "", "", ""],
    ["好辛苦", "hǎo xīn kǔ", "so tiring / hard work", "tersangat memenatkan letih"],
    ["”", "", "", ""],
    ["时", "shí", "when", "waktu itu punya kala"],
    ["，", "", "", ""],
    ["我怎么说的", "wǒ zěn me shuō de", "how did I say it", "bagaimanakah yang saya katakan pula"],
    ["吗", "ma", "particle", "kah"],
    ["？", "", "", ""],
    ["我说", "wǒ shuō", "I said", "Saya berkata ketika itu bahawa"],
    ["养孩子", "yǎng hái zi", "rearing children", "membela anak-anak kecil itu"],
    ["固然", "gù rán", "admittedly / of course", "memang tidak diakui akal membawa"],
    ["辛苦", "hān kǔ", "tiring / hard", "keletihan penat lelah"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "namun begitu semestinya jua"],
    ["正因为有苦", "zhèng yīn wèi yǒu kǔ", "exactly because there is bitterness", "justeru kerana adanya rasa pahit maung penat"],
    ["才有乐", "cái yǒu lè", "then can have joy / happiness", "barulah akan menikmati kemanisan riang gembira"],
    ["。", "", "", ""],
    ["孩子", "hái zi", "The child", "Anak kecil itu"],
    ["这次", "zhè cì", "this time", "kali ini kebetulan exam"],
    ["考糟了", "kǎo zāo le", "scored terribly / flunked", "score dah rosak teruk hancur"],
    ["，", "", "", ""],
    ["下次", "xià cì", "next time", "kali depan esok kelak"],
    ["考好了", "kǎo hǎo le", "scored well", "bila dapat score cemerlang cemerlang"],
    ["，", "", "", ""],
    ["苦", "kǔ", "bitterness / pain", "segala kepahitan lelah"],
    ["变成乐", "biàn chéng lè", "changed into joy", "bertukar menjadi kemanisan riang"],
    ["；", "", "", ""],
    ["孩子", "hái zi", "the child", "anak kecil itu"],
    ["前天", "qián tiān", "the day before yesterday", "hari sebelum semalam kebetulan"],
    ["病了", "bìng le", "fell sick", "jatuh sakit demam"],
    ["，", "", "", ""],
    ["今天", "jīn tiān", "today", "hari ini tiba-tiba"],
    ["退烧了", "tuì shāo le", "fever receded", "dah kebah demam panasnya"],
    ["，", "", "", ""],
    ["担忧", "dān yōu", "worry / anxiety", "segala kerisauan bimbang hati"],
    ["成了欣喜", "chéng le xīn xǐ", "became delight / joy", "bertukar menjadi kegembiraan syukur yang amat sangat"],
    ["。", "", "", ""],
    ["我又说", "wǒ yòu shuō", "I again said", "Saya pula menambah berkata lagi"],
    ["“", "", "", ""],
    ["人生", "rén shēng", "human life", "riwayat hidup manusia"],
    ["如果只是一根", "rú guǒ zhǐ shì yì gēn", "if only was a single string of", "sekiranya hanya sekadar sebaris tali"],
    ["平平的线", "píng píng de xiàn", "flat / straight line", "garisan yang lurus mendatar sahaja"],
    ["，", "", "", ""],
    ["多没意思", "duō méi yì si", "how meaningless / boring", "masakan tersangat membosankan tidak ada erti"],
    ["？", "", "", ""],
    ["一定要", "yí dìng yào", "definitely must", "ia semestinya wajib wajib jua"],
    ["起起伏伏", "qǐ qǐ fú fú", "ups and downs", "mempunyai pasang surut naik turun"],
    ["，", "", "", ""],
    ["有付出", "yǒu fù chū", "have exertion / devotion", "ada pengorbanan dicurahkan"],
    ["，", "", "", ""],
    ["有获得", "yǒu huò dé", "have acquisition / reward", "ada hasil pulangan dinikmati"],
    ["，", "", "", ""],
    ["才丰富", "cái fēng fù", "only then rich / colorful", "barulah ia akan menjadi kaya-raya berseri dan bermakna"],
    ["”", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 17 段
    ["那么", "nà me", "Then / in that case", "Oleh yang demikian halnya sekarang"],
    ["，", "", "", ""],
    ["我现在", "wǒ xiàn zài", "I right now", "saya pada saat ini jua"],
    ["也要对你说", "yě yào duì nǐ shuō", "also want to say to you", "turut wajib berkata kepada kamu jua"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["人生", "rén shēng", "life", "riwayat hidup manusia itu"],
    ["就是", "jiù shì", "exactly is", "sememangnya adalah"],
    ["要有成功", "yào yǒu chéng gōng", "must have success", "wajib mengandungi kejayaan manis"],
    ["、", "", "", ""],
    ["有失败", "yào yǒu shī bài", "have failure", "ada kegagalan pahit"],
    ["，", "", "", ""],
    ["才有意思", "cái yǒu yì si", "only then interesting / meaningful", "barulah akan mempunyai makna dan erti hidup"],
    ["。”", "", "", ""],
    ["你今天", "nǐ jīn tiān", "you today", "Kamu hari ini kebetulan exam"],
    ["失败了", "shī bài le", "failed", "dapat keputusan hancur gagal"],
    ["，", "", "", ""],
    ["痛定思痛", "tòng dìng sī tòng", "reflecting deeply after pain / draw lessons from bitter experience", "menangis hiba merenung kesilapan lalu selepas derita pahit"],
    ["，", "", "", ""],
    ["检讨改进", "jiǎn tǎo gǎi jìn", "reviewing and improving", "membuat post-mortem menyemak dan membaiki diri"],
    ["，", "", "", ""],
    ["明天", "míng tiān", "tomorrow", "esok kelak masa depan"],
    ["反败为胜", "fǎn bài wéi shèng", "turn defeat into victory", "pasti boleh bangkit menebus kekalahan bertukar johan"],
    ["，", "", "", ""],
    ["多棒", "duō bàng", "how wonderful / excellent", "alangkah hebat cantiknya kagum"],
    ["！", "", "", ""],
    ["而且如果你能", "ér qiě rú guǒ nǐ néng", "and furthermore if you can", "malah lagipun sekiranya kamu berupaya"],
    ["由今天的小考中", "yóu jīn tiān de xiǎo kǎo zhōng", "from today's quiz within", "daripada dalam ujian kuiz kecil hari ini"],
    ["得到教训", "dé dào jiào xun", "obtain lesson", "mendapat iktibar teladan dan pengajaran"],
    ["，", "", "", ""],
    ["使你明天的大考", "shǐ nǐ míng tiān de dà kǎo", "make your tomorrow's major exam", "menyebabkan kamu punya peperiksaan besar esok hari kelak"],
    ["不再犯错", "bú zài fàn cuò", "no longer make mistakes", "langsung tidak akan mengulangi kesilapan silap buat lagi"],
    ["，", "", "", ""],
    ["这小考", "zhè xiǎo kǎo", "this quiz", "kuiz kecil hari ini punya ujian"],
    ["不就像", "bú jiù xiàng", "is it not just resemble", "bukankah ia adalah bagaikan mirip"],
    ["注射疫苗", "zhù shè yì miáo", "injecting vaccine", "mencucuk ubat cecair suntikan vaksin"],
    ["，", "", "", ""],
    ["小小疼一下", "xiǎo xiǎo téng yí xià", "hurts a tiny little bit once", "merasa senak sakit sedikit sahaja sekejap"],
    ["，", "", "", ""],
    ["却能避免", "què néng bì miǎn", "yet can avoid", "sebaliknya mampu mengelak diri daripada"],
    ["得大病吗", "dé dà bìng ma", "getting major illness", "mendapat serangan penyakit gergasi parah kah"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第 18 段
    ["亲爱的", "qīn ài de", "Dear / beloved", "Wahai anakku kesayangan yang tersangat dihormati"],
    ["小丫头", "xiǎo yā tou", "little girl", "gadis kecil comel / anak perempuan"],
    ["，", "", "", ""],
    ["别再为", "bié zài wèi", "don't any longer because of", "janganlah asyik lagi disebabkan kerana"],
    ["人家考得好", "rén jia kǎo de hǎo", "other people scored well", "orang lain dapat score cemerlang cemerlang"],
    ["，", "", "", ""],
    ["你考糟而", "nǐ kǎo zāo ér", "you scored terribly and thereby", "kamu dapat score hancur lalu merajuk hiba"],
    ["伤心了吧", "shāng xīn le ba", "be heartbroken", "sedih luluh hati dah lah"],
    ["！", "", "", ""],
    ["你甚至", "nǐ shèn zhì", "You even", "Kamu malah bahkan jua sepatutnya"],
    ["应该为", "yīng gāi wèi", "should because of", "harus disebabkan kerana melihat"],
    ["那些顽皮男生", "nà xiē wán pí nán shēng", "those mischievous boys", "budak-budak lelaki yang degil nakal itu"],
    ["，", "", "", ""],
    ["居然能", "jū rán néng", "unexpectedly can", "rupa-rupanya di luar jangkaan boleh jua"],
    ["拿回家", "ná huí jiā", "bring back home", "membawa balik ke rumah mereka"],
    ["一张", "yì zhāng", "a (measure word for report card)", "sehelai kertas keputusan"],
    ["90分的成绩单", "jiǔ shí fēn de chéng jī dān", "90 marks report card", "sembilan puluh markah punya slip exam"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then / right after", "kemudian selepas itu melihat mereka"],
    ["得意地", "dé yì de", "proudly / triumphantly", "dengan penuh kembang hidung tersenyum menang"],
    ["说", "shuō", "saying", "berkata mendakwa bahawa"],
    ["他赢了你", "tā yíng le nǐ", "he beat you", "dia telah berjaya menewaskan kamu johan"],
    ["而高兴呢", "ér gāo xìng ne", "and thereby feel happy", "lalu turut berasa tumpang gembira riang jua lah"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 19 段
    ["有赢有输", "yǒu yíng yǒu shū", "Having wins and losses", "Mempunyai menang johan dan kalah tewas"],
    ["，", "", "", ""],
    ["才是", "cái shì", "only then is", "barulah semestinya adalah dinamakan sebuah"],
    ["多彩的", "duō cǎi de", "colorful / splendid", "yang berwarna-warni berseri-seri punya"],
    ["人生啊", "rén shēng ā", "human life", "riwayat hidup manusia jua lah"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 出处补齐 (完美清洗，干净利落)
    ["（", "", "", ""],
    ["刘墉", "liú yōng", "Liu Yong (Author)", "Liu Yong (Penulis)"],
    ["《", "", "", ""],
    ["有输有赢才是人生", "yǒu yíng yǒu shū cái shì rén shēng", "Winning and Losing is True Life", "Menang Kalah Itulah Kehidupan"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
